--------------------------------------------------------
--  DDL for Table REL_EX
--------------------------------------------------------

  CREATE TABLE "GEFA0728"."REL_EX" 
   (	"REFERENCEID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"TABLENAME" VARCHAR2(200 BYTE), 
	"COLUMNNAME" VARCHAR2(200 BYTE), 
	"REFERREDTABLENAME" VARCHAR2(200 BYTE), 
	"REFERREDCOLUMNNAME" VARCHAR2(200 BYTE), 
	"TOPOLOGYORDERNUM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USER01" ;

--------------------------------------------------------
--  Constraints for Table REL_EX
--------------------------------------------------------

  ALTER TABLE "GEFA0728"."REL_EX" MODIFY ("REFERENCEID" NOT NULL ENABLE);
